version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - url-shortener-network
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    command: npm start
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - url-shortener-network
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo:4.0.27-xenial
    ports:
      - 27017:27017
    networks:
      - url-shortener-network
    volumes:
      - mongo-data:/data/db

networks:
  url-shortener-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

